language: java
sudo: required
services: mongodb

jdk:
  - oraclejdk8



before_install:
  - chmod +x gradlew
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
    - wget https://services.gradle.org/distributions/gradle-3.5-bin.zip
    - unzip gradle-3.5-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.5
    - export PATH=$GRA1DLE_HOME/bin:$PATH
    
script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
